name: Sync Issues to Private Repos
on:
  issues:
    types: [opened, edited]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse and Mirror Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PRIVATE_REPOS_TOKEN }}  # PAT with access to both privates
          script: |
            const { Octokit } = require('@octokit/action');
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            
            // Get issue details
            const issue = await octokit.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            // Parse YAML frontmatter from body (template embeds as --- YAML ---)
            const body = issue.data.body || '';
            const yamlMatch = body.match(/---\s*([\s\S]*?)\s*---/);
            let platform = 'untriaged';
            if (yamlMatch && yamlMatch[1]) {
              const yamlLines = yamlMatch[1].split('\n');
              const platformLine = yamlLines.find(line => line.trim().startsWith('platform:'));
              if (platformLine) {
                platform = platformLine.split(':')[1].trim().toLowerCase();
              }
            }
            
            // Determine target repo
            let targetRepo;
            if (platform.includes('web')) {
              targetRepo = 'caninesportshub';
            } else if (platform.includes('phone') || platform.includes('tablet')) {
              targetRepo = 'mobil';
            } else {
              // Fallback: Label as untriaged in public repo
              await octokit.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['untriaged']
              });
              console.log('No platform selected - labeled untriaged');
              return;
            }
            
            // Create mirrored issue in target private repo
            await octokit.rest.issues.create({
              owner: context.repo.owner,
              repo: targetRepo,
              title: `[Public #${context.issue.number}] ${issue.data.title}`,
              body: `Synced from public: ${issue.data.html_url}\n\n${body}`,
              labels: ['synced', 'bug']  // Add custom labels, e.g., 'flyball'
            });
            
            // Optional: Comment on public issue
            await octokit.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `This issue has been mirrored to the ${platform} private repo for tracking. Thanks!`
            });
